import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Hello Twitter</h1>

    </div>
  )
}
